{{ config(materialized = 'table') }}

WITH FACT_TRADES_CTE AS (
    SELECT
        -- Surrogate primary key

        -- Foreign key to dim_exchange
        MD5(UPPER(TRIM(COALESCE(SECURITYEXCHANGE, '')))) AS EXCHANGE_ID,

        -- Date key
        TO_NUMBER(TO_CHAR(TRADEDATE, 'YYYYMMDD')) AS DATE_ID,

        -- Grain + dimensions
        MD5(
            UPPER(TRIM(SYMBOL)) || '-' || 
            UPPER(TRIM(INST_UND_PROD_TYP)) || '-' || 
            UPPER(TRIM(ASSET)) || '-' || 
            UPPER(TRIM(UNDERLYINGPRODUCT)) || '-' || 
            UPPER(TRIM(SECURITYID)) || '-' || 
            UPPER(TRIM(SECURITYTYPE))
        ) AS commodity_id,
        
        -- Fact measures
        COALESCE(TRADEQUANTITY, '0') AS TRADEQUANTITY,
        COALESCE(LEVEL1ASKQUANTITY, '0') AS LEVEL1ASKQUANTITY,
        COALESCE(LEVEL1BIDORDER, '') AS LEVEL1BIDORDER,
        COALESCE(TRANSACTTIME, NULL) AS TRANSACTTIME,
        COALESCE(LEVEL1ASKORDER, '') AS LEVEL1ASKORDER,
        COALESCE(TRADEPRICE, '0') AS TRADEPRICE,
        COALESCE(CURRENCYCODE, '') AS CURRENCYCODE,
        COALESCE(LEVEL1ASKPRICE, '0') AS LEVEL1ASKPRICE,
        COALESCE(LEVEL1BIDPRICE, '0') AS LEVEL1BIDPRICE,
        COALESCE(LEVEL1BIDQUANTITY, '0') AS LEVEL1BIDQUANTITY
    FROM RAW_DATA
    WHERE TRADEDATE IS NOT NULL AND SECURITYEXCHANGE IS NOT NULL
)

SELECT * FROM FACT_TRADES_CTE 

